version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload files to S3
          command: aws s3 sync src s3://benpapillon.com/ --delete --acl=public-read
      - run:
          name: Invalidate CloudFront cache
          command: aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $BENPAPILLONCOM_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          context: aws
          filters:
            branches:
              only: master
